name: json_api_client
description: api client for jsonplaceholder
publish_to: none

environment:
  sdk: ">=2.19.0 <3.0.0"

dependencies: 
  dio: ^5.1.1
  retrofit: ^4.0.1

dev_dependencies:
  build_runner: ^2.3.3
  flutter_test:
    sdk: flutter
  retrofit_generator: ^6.0.0+3
