name: json_bloc_ui
description: bloc widgets and utils
publish_to: none

environment:
  sdk: ">=2.19.0 <3.0.0"

dependencies:
  equatable: ^2.0.5

dev_dependencies:
  build_runner: ^2.3.3
  flutter_test:
    sdk: flutter
