name: json_repository
description: repository for jsonplaceholder
publish_to: none

environment:
  sdk: ">=2.19.0 <3.0.0"

dependencies:
  equatable: ^2.0.5
  json_annotation: ^4.8.1
  json_api_client:
    path: ../json_api_client
  database_client:
    path: ../database_client
  drift: ^2.7.0


dev_dependencies:
  build_runner: ^2.3.3
  flutter_test:
    sdk: flutter
  json_serializable: ^6.6.2
  retrofit_generator: ^6.0.0+3
